### ISSUE TITLE
新功能建议：显示设置中增加对虚拟终端字体、字号、行间距的设置选项

### ISSUE THREAD

**Issue by think3t** [AntSwordProject/antSword#203]
- [x] 这是一个新功能的建议

---

## 新功能建议

- [x] 我确定我所提的新功能不在[待做事项](https://github.com/AntSwordProject/AntSword/blob/master/CHANGELOG.md#待做事项)内，也不在issue列表
- [x] 我确定我所提出的新功能是为了方便在网站管理，而不是用于非法用途

### 新功能描述

显示设置中增加对虚拟终端字体、字号、行间距的设置选项，高分辨率下字体太小。

**Comment by yzddmr6** [comment]
+1 
不然每次都要手动按ctrl + -。。

**Comment by think3t** [comment]
@yzddmr6 我直接修改了`static/libs/terminal/css/jquery.terminal-1.1.1.css`文件，把字体大小和行间距调大了。
```css
    .terminal, .cmd, .terminal .terminal-output div div, .cmd .prompt {
        font-size: calc(var(--size, 1) * 16px);
        line-height: calc(var(--size, 1) * 18px);
    }
```
