### ISSUE TITLE
[BUG] 加载器加载失败 提示为[Object Object] 

### ISSUE THREAD

**Issue by jingyuexing** [AntSwordProject/antSword#293]
- [x] 我确定这是蚁剑本身的一个 Bug，我并不是在询问如何使用蚁剑
- [x] 我确定已经将蚁剑升级至[软件发布页面](https://github.com/AntSwordProject/AntSword/releases)中的**最新版**
- [ ] 我已经阅读过蚁剑的开发文档，并且尝试过自己通过Google等方式解决问题
- [ ] 这是一个新功能的建议
- [ ] 我查阅了文档没找到解决方案，所以来询问如何使用蚁剑

---

## 报告 Bug

- [ ] 我使用的操作系统是 ***macOS*** 10+
- [ ] 我使用的操作系统是 ***Debian/Ubuntu*** GNU/Linux
- [ ] 我使用的操作系统是 ***Fedora*** GNU/Linux
- [ ] 我使用的操作系统是 ***Arch*** GNU/Linux
- [ ] 我使用的操作系统是 ***Other*** GNU/Linux
- [x] 我使用的操作系统是 ***Windows*** 10+

---

- [ ] 我使用的是 32 位操作系统
- [x] 我使用的是 64 位操作系统

### Bug 详细描述

加载器解压失败,也许是因为npm包文件夹路径过长导致的
---

## 新功能建议

- [ ] 我确定我所提的新功能不在[待做事项](https://github.com/AntSwordProject/AntSword/blob/master/CHANGELOG.md#待做事项)内，也不在issue列表
- [ ] 我确定我所提出的新功能是为了方便在网站管理，而不是用于非法用途

### 新功能描述

我觉得，直接使用Github的Action 自动布置，自动发布更加好，加载器经常加载不了
---

### shell 连接 Bug

1. 服务端操作系统

2. 服务端shell代码

3. 服务端环境配置

4. 客户端连接配置

**Comment by jingyuexing** [comment]
对于加载器真的很无语

**Comment by jingyuexing** [comment]
```yaml
on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**'    # Push events to every tag including hierarchical tags like v1.0/beta 这一步是给push tag绑定一个事件
```

```yaml
jobs:
  build:
    runs-on: ubuntu-latest  # 容器
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag  #切换到Tag所在的提交
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: BUILD
        run: |
            npm install
            npm run build
      - name: Create a GitHub release  #创建github 发布版本
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }} #标签名
          release_name: Release ${{ steps.tag_version.outputs.new_tag }} #版本名
          body: ${{ steps.tag_version.outputs.changelog }}  # 更新日志
          files: |   # 要发布的文件
            dist/*
```
